# Site settings
title: Christopher Siegel
email: hello@christopher-siegel.de
description: "I design and craft beautiful user experiences that are easy to use on all devices. Design, Code, Advance."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: plausiegel
github_username:  christopher-siegel

# Build settings
markdown: kramdown
permalink: pretty
